server {
  listen 80;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri /index.html;
  }

  location /measurements {
    proxy_pass http://backend:8000;
  }

  location /upload {
    proxy_pass http://backend:8000;
  }

    location /stats {
    proxy_pass http://backend:8000;
  }
}