services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - TZ=Europe/Berlin   
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - db-data:/app/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  db-data: